import { Component, ElementRef, ViewChild } from '@angular/core';
import { ReactiveFormsModule, FormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { NgbAlertModule, NgbDatepickerModule, NgbDateStruct } from '@ng-bootstrap/ng-bootstrap';
import { CommonModule, DatePipe } from '@angular/common'
import { DocsExampleComponent } from '@docs-components/public-api';
import {
  RowComponent, ColComponent, TextColorDirective, CardComponent, CardHeaderComponent,
  CardBodyComponent, InputGroupComponent, InputGroupTextDirective, FormControlDirective,
  FormLabelDirective, FormCheckInputDirective, ButtonDirective, ThemeDirective,
  DropdownComponent, DropdownToggleDirective, DropdownMenuDirective, DropdownItemDirective,
  DropdownDividerDirective, FormSelectDirective
} from '@coreui/angular';
import { ToastrService } from "ngx-toastr";
import { NgxSpinnerService } from "ngx-spinner";
import { StudentService } from '../../../services/student.service';
import { AuthenticationService } from '../../../services/authentication.service';

@Component({
  selector: 'add-student',
  templateUrl: './addstudent.component.html',
  styleUrls: ['./addstudent.component.scss'],
  standalone: true,
  imports: [RowComponent, ColComponent, TextColorDirective, CardComponent, CardHeaderComponent,
    CardBodyComponent, DocsExampleComponent, InputGroupComponent, InputGroupTextDirective,
    FormControlDirective, FormLabelDirective, FormCheckInputDirective, ButtonDirective, ThemeDirective,
    DropdownComponent, DropdownToggleDirective, DropdownMenuDirective, DropdownItemDirective, RouterLink,
    DropdownDividerDirective, FormSelectDirective, ReactiveFormsModule, FormsModule, CommonModule,
    NgbDatepickerModule, NgbAlertModule]
})
export class AddStudentComponent {
  [x: string]: any;
  submitted = false;
  currentUser: any;
  selectedFile: File | undefined;
  nssycodeAutogenerated: string = '';
  addStudentForm: FormGroup | any;
  @ViewChild('inputFile') myInputVariable!: ElementRef;
  selectdob!: NgbDateStruct;
  sexList: string[] = ['Male', 'Female'];
  religiousList: string[] = ['Hinduism', 'Islam', 'Christianity', 'Sikhism', 'Buddhism', 'Jainism'];
  castRList: string[] = ['SC', 'ST', 'Minority', 'General'];
  fileData!: File | string;
  previewUrl: any = null;
  fileUploadProgress!: string;
  uploadedFilePath!: string;

  formData = new FormData();
  imageURL!: string;
  ifchanchepic: boolean = false;

  constructor(private formBuilder: FormBuilder,
    private studentService: StudentService,
    private datePipe: DatePipe,
    private toastr: ToastrService,
    private spinner: NgxSpinnerService,
    private authenticationService: AuthenticationService
  ) {
    this.authenticationService.currentUser.subscribe(x => this.currentUser = x);
  }

  ngOnInit() {
    this.addStudentForm = this.formBuilder.group({
      stu_name: ['', Validators.required],
      paddress: ['', Validators.required],
      peraddress: [''],
      nationality: [''],
      mobile: ['', Validators.required],
      guardian: ['', Validators.required],
      emaiid: [''],
      religion: ['Hinduism'],
      casts: ['SC'],
      sex: ['Male'],
      exam: [''],
      duration: [''],
      university: [''],
      regno: [''],
      percentage: [''],
      class_per: [''],
      fileup_ins: [''],
      center_code: [''],
      center_name: [''],
      nSSY_code: [''],
      r1: [''],
      r2: [''],
      r3: [''],
      r4: [''],
      r5: [''],
      act: [''],
      name: ['']
    });
    this.Idnumber();
  }
  get f() { return this.addStudentForm.controls; }

  onAddStudentSubmit() {
    this.spinner.show();
    this.submitted = true;
    if (this.addStudentForm.invalid) {
      this.spinner.hide();
      return;
    }
    if (!this['selectdob']) {
      this.toastr.warning('Warning', "Enter Date of birth");
      this.spinner.hide();
      return;
    }
    const addstudent = {
      stu_name: this.f.stu_name.value,
      paddress: this.f.paddress.value,
      peraddress: this.f.peraddress.value,
      nationality: this.f.nationality.value,
      mobile: this.f.mobile.value,
      guardian: this.f.guardian.value,
      emaiid: this.f.emaiid.value,
      religion: this.f.religion.value,
      dob: this.datePipe.transform(new Date(this.selectdob.year, this.selectdob.month - 1, this.selectdob.day), 'MM/dd/yyyy'),
      casts: this.f.casts.value,
      sex: this.f.sex.value,
      exam: this.f.exam.value,
      university: this.f.university.value,
      percentage: this.f.percentage.value,
      fileup_ins: this.f.fileup_ins.value,
      center_code: this.currentUser.id,//this.f.center_code.value,
      center_name: this.currentUser.bname,//this.f.center_name.value,
      nSSY_code: this.f.nSSY_code.value
    }
    this.studentService.createStudent(addstudent).subscribe((res: any) => {
      if (res && res > 0) {
        this.clearDate();
        this.toastr.success('Success', "Student Inserted Successfully");
        if (this.ifchanchepic) {
          this.uploadImage();
        }
        else {
          this.Idnumber();
          this.spinner.hide();
        }
      }
      else {
        this.toastr.warning('Warning', "Data Exits");
        this.spinner.hide();
      }
    });
  }
  onSelectDate(date: NgbDateStruct) {
    this.selectdob = date;// new Date(date.year, date.month - 1, date.day);   
  }
  private reset() {
    this.addStudentForm.reset();

  }
  private clearDate() {
    this.addStudentForm.get('stu_name').setValue('');
    this.addStudentForm.get('paddress').setValue('');
    this.addStudentForm.get('peraddress').setValue('');
    this.addStudentForm.get('guardian').setValue('');
    this.myInputVariable.nativeElement.value = '';
    this.imageURL = '';
  }
  sameAddress(isChecked: any) {
    if (isChecked) {
      this.addStudentForm.get('peraddress').setValue(this.f.paddress.value);
    }
    else {
      this.addStudentForm.get('peraddress').setValue('');
    }

  }
  private uploadImage() {
    this.formData = new FormData();
    this.formData.append('images', this.fileData);
    this.formData.append('nssycode', this.f.nSSY_code.value);
    this.studentService.uploadStudentImage(this.formData).subscribe((res: any) => {
      if (res) {
        this.ifchanchepic = false;
        this.spinner.hide();
        this.Idnumber();
        this.toastr.success('Success', "Image Inserted Successfully");
      }
      else {
        this.spinner.hide();
      }
    });
  }

  public Idnumber() {
    let st1 = this.currentUser.id;
    let count = 0;
    this.spinner.show();
    let bcode = this.currentUser.id;
    let likestr = "SNYWB" + ("000" + st1).slice(-3) + "/" + new Date().getFullYear() % 100 + "/";
    this.studentService.branchStudentRegisCount(bcode, likestr).subscribe((res: any) => {
      if (res && res > 0) {
        count = res + 1;
        this.spinner.hide();
      }
      else {
        count = 1;
        this.spinner.hide();
      }
      this.nssycodeAutogenerated = "SNYWB" + ("000" + st1).slice(-3) + "/" + new Date().getFullYear() % 100 + "/" + ("000" + count).slice(-3);
      this.addStudentForm.get('nSSY_code').setValue(this.nssycodeAutogenerated);
    });
    this.addStudentForm.get('center_name').setValue(this.currentUser.bname);
    this.addStudentForm.get('center_code').setValue(this.currentUser.id);

  }

  // Image Preview  bjgjd
  showPreview(event: any) {
    this.ifchanchepic = true;
    this.selectedFile = <File>event.target.files[0];
    const file = (event.target as HTMLInputElement | any).files[0];
    this.fileData = file;
    // File Preview
    const reader = new FileReader();
    reader.onload = (e) => {
      this.imageURL = reader.result as string;
    }
    reader.readAsDataURL(file);

  }

}
